#!/usr/bin/env bash
# Run the tests (matches GitHub workflows)

# Non-interactive plots
export SCIRIS_BACKEND='agg'

section() { printf '\n\033[1;91m── %s ──\033[0m\n\n' "$*"; }

section "Python tests"
pytest -v

section "R tests"
Rscript -e "testthat::test_dir('tests', stop_on_failure = TRUE)"
