name: Python Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: bash install_python.sh

      - name: Run tests
        run: pytest -v
